---
# tasks file for registry
- name: For docker-ce and jenkins installation
  dnf:
          name:
               - docker-ce
          skip_broken: yes
          state: present 
- pip:
        name: docker

- name: Installing docker-compose
  copy: 
          src: docker-compose
          dest: /usr/local/bin/
          mode: '0777'  

- name: Pull default Docker image
  docker_image:
          name: centos:latest
          source: pull

- name: run the service defined in my docker-compose.yml
  docker_compose:
         project_src: docker-compose.yml
