---
# tasks file for registry
- name: For docker-ce and jenkins installation
  dnf:
          name:
               - docker-ce
          skip_broken: yes
          state: present 
- name: Installing docker-compose
  copy: 
          src: docker-compose
          dest: /usr/local/bin/
          mode: '0777'     
