---
# tasks file for registry
- name: For docker-ce and jenkins installation
  dnf:
          name:
               - docker-ce
          skip_broken: yes
          state: present 
- pip:
        name: docker
- pip:
        name: docker-compose

- name: Installing docker-compose
  copy: 
          src: docker-compose
          dest: /usr/local/bin/
          mode: '0777'  

- name: Pull default Docker image
  docker_image:
          name: centos:latest
          source: pull

- name: getting docker-compose ready
  copy:
          src: /root/Desktop/workspace/ansible/roles/registry/files/docker-compose.yml
          dest: /root/Desktop/
          mode: '0777'


- name: run the service defined in my docker-compose.yml
  docker_compose:
         project_src: /root/Desktop/docker-compose.yml
