---
# tasks file for configure
- name: Required packages for guest additions installation 
  package:
          name:
               - platform-python-devel
               - gcc
               - perl
               - make
               - kernel-headers
               - kernel-devel
               - elfutils-libelf-devel
          state: present        
- name: copy the commit and push command
  copy:
          src: 
               - commit 
               - push
          dest: /usr/bin/
          owner: root
          group: root
          mode: u=rwx,g=rwx,o=rwx 
