---
# tasks file for configure
- name: Required packages for guest additions installation 
  package:
          name:
               - platform-python-devel
               - gcc
               - perl
               - make
               - kernel-headers
               - kernel-devel
               - elfutils-libelf-devel
          state: present
- name: For docker-ce and jenkins installation
  dnf:
          name:
               - docker-ce
               - jenkins
               - java-1.8.0-openjdk
          skip_broken: yes
          state: present          
