---
# tasks file for machine
- package:
          name: 
               - platform-python-devel
               - gcc 
               - perl
               - make
          state: present


- pip:
      name:
           - numpy
           - pandas
           - scikit-learn
           - folium
